ARG VERSION=11.5.2

FROM grafana/grafana-oss:${VERSION}

# copy provisioning config
COPY datasources /etc/grafana/provisioning/datasources
COPY alerting /etc/grafana/provisioning/alerting
COPY dashboards /etc/grafana/provisioning/dashboards
